export const AGORA_APP_ID = process.env.AGORA_APP_ID!;
export const AGORA_APP_CERTIFICATE = process.env.AGORA_APP_CERTIFICATE || "";
export const AGORA_APP_TOKEN =
  "007eJxTYPA1C5jlmXiDM3Zq88WaaXMSDDep81/k4/x0Za7hHpZrVcsUGFJMky0tUyxTk5OMLEySUwwsDNKSDRJNk40s0ixNzZLTMlhF0xsCGRmEz4myMjJAIIjPypBYlJOYx8AAAP3GHdg=";
